### PR TITLE
Updated S3 Credentials management example

### PR DESCRIPTION
**Pull request by csaranbalaji**
Resolves https://github.com/quantumblacklabs/kedro-training/issues/3

### CODE REVIEW

**Comment by csaranbalaji** [comment]
@MerelTheisenQB Could you please check this?

**Review by 921kiyo — APPROVED** [review]
👍

**Review by laisbsc — APPROVED** [review]
👍 Thanks for the contribution!

**Comment by csaranbalaji** [comment]
@laisbsc @921kiyo Could you please merge this PR to master?

**Comment by csaranbalaji** [comment]
@921kiyo Could you please add `hacktoberfest-accepted` label to this PR if possible?

**Pull request merged**
